version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore:"
    reviewers:
      - "Lucasbeneston"

  - package-ecosystem: "npm"
    directory: "/public_website"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore:"
    reviewers:
      - "Lucasbeneston"

  - package-ecosystem: "npm"
    directory: "/content_management_system"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore:"
    reviewers:
      - "Lucasbeneston"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore:"
    reviewers:
      - "Lucasbeneston"
