version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "(BSR) chore(deps):"
    reviewers:
      - "Lucasbeneston"

  - package-ecosystem: "npm"
    directory: "/public_website"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "(BSR) chore(deps):"
    reviewers:
      - "Lucasbeneston"

  - package-ecosystem: "npm"
    directory: "/content_management_system"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "(BSR) chore(deps):"
    reviewers:
      - "Lucasbeneston"
