version: "3"
services:
  next_preview:
    build:
      context: public_website
      args:
        network_mode: proxy
    env_file:
      - public_website/.env
    environment:
      ID_TOKEN: "dummy_token"
      NEXT_PUBLIC_BACKEND_API_URL: https://backend.passculture.app
    ports:
      - 3000:3000

  cms:
    build:
      context: content_management_system
    ports:
      - 1337:1337
    env_file: content_management_system/.env
    environment:
      DATABASE_HOST: database
      GCS_BUCKET_NAME: "fake"
    depends_on:
      - database

  database:
    image: "postgres:16.0"
    ports:
      - 5432:5432
    env_file: content_management_system/.env
    volumes:
      - ./data/:/var/lib/postgresql/data/
