export const PATHS = {
  NEWS: 'news-list',
  SIMULATOR: 'simulator',
  RESSOURCES_PASS: 'ressourcespass',
  RESSOURCES_PASS_PAGE: 'ressources-pass-culture',
  RESSOURCES_TEACHERS_PAGE: 'ressources-enseignant',
  EVENTS: 'events',
  PAGES: 'pages',
  LISTE_JEUNES: 'liste-jeune',
  ACTU_PASS: 'actualites-pass-culture',
  ACTU_RDV_ACTEURS: 'actualites-rdv-acteurs-culturel',
  HELP_CULTURAL_ACTORS: 'help-cultural-actors',
  HELP_TEACHERS: 'help-teachers',
  HELP: 'help',
  RESOURCES: 'resources',
  HOME: 'home',
  OFFERS_LIST: 'liste-offre',
  PRESSE: 'presse',
  ETUDES_PASS_PAGE: 'etudes-pass-culture',
}
