/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import sitemap from "strapi-plugin-sitemap/strapi-admin";
import updateStaticContent from "strapi-plugin-update-static-content/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    seo: seo,
    "users-permissions": usersPermissions,
    "multi-select": multiSelect,
    sitemap: sitemap,
    "update-static-content": updateStaticContent,
  },
});
