/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import graphql from "@strapi/plugin-graphql/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import updateStaticContent from "../../src/plugins/update-static-content/./dist/admin/index.mjs";
import sitemap from "../../src/plugins/sitemap/./dist/admin/index.mjs";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    graphql: graphql,
    seo: seo,
    "users-permissions": usersPermissions,
    "multi-select": multiSelect,
    "update-static-content": updateStaticContent,
    sitemap: sitemap,
  },
});
