name: Build docker image 

on:
  pull_request:

jobs:
  build-changed-images:
    uses: ./.github/workflows/reusable_docker_build.yml
    permissions:
      id-token: write
      contents: write
    with:
      image: pc-institutional 
      push: true 
      context: content_management_system
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      ARTIFACT_REGISTRY_SERVICE_ACCOUNT: ${{ secrets.ARTIFACT_REGISTRY_SERVICE_ACCOUNT }}


