name: Check no dead code is introduced

on:
  pull_request:
    branches: main
    types:
      - opened
      - edited
      - synchronize

jobs:
  yarn-ts-prune:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pass-culture/common-workflows/actions/setup-safe-chain@9a5f036470496551365fe9c26afbd4febe20a8cb
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: "public_website/.nvmrc"
      - name: Install dependencies
        run: yarn setup
      - name: Dead code scan
        run: ./scripts/check_dead_code_introduced.sh
