on:
  workflow_dispatch:

name: Deploy production CMS and static website

permissions:
  id-token: write
  contents: read

jobs:
  build-image-cms:
    runs-on: ubuntu-22.04
    environment:
      name: site-instit-production
      deployment: false
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Authentification to Google to get secret
      uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc0933' # v3.0.0
      with:
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PRD }}
        service_account: ${{ vars.SITE_INSTIT_CD_SERVICE_ACCOUNT }}
    - name: build image
      id: 'build'
      uses: pass-culture/common-workflows/actions/build-docker-image@main
      with:
        image: pc-institutional 
        push: true 
        context: content_management_system
        gcp_workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PRD }}
        artifact_registry_service_account: ${{ vars.SITE_INSTIT_CD_SERVICE_ACCOUNT }}
        cosign_kms_key: ${{ vars.COSIGN_KMS_KEY }}

  build-image-public-site-preview:
    runs-on: ubuntu-22.04
    environment:
      name: site-instit-production
      deployment: false
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Authentification to Google to get secret
      uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc0933' # v3.0.0
      with:
        workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PRD }}
        service_account: ${{ vars.SITE_INSTIT_CD_SERVICE_ACCOUNT }}
    - name: build image
      id: 'build'
      uses: pass-culture/common-workflows/actions/build-docker-image@main
      with:
        image: pc-institutional-public-site-preview
        push: true 
        context: public_website
        gcp_workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PRD }}
        artifact_registry_service_account: ${{ vars.SITE_INSTIT_CD_SERVICE_ACCOUNT }}
        cosign_kms_key: ${{ vars.COSIGN_KMS_KEY }}

  deploy-cms-production:
    uses: ./.github/workflows/reusable_cms_deploy.yml
    needs: 
      - build-image-cms
      - build-image-public-site-preview
    with:
      project_id: passculture-cls-metier-prod
      environment: production
      cluster_name: cls-metier-production
      gcp_project_id: passculture-cls-metier-prod
      cluster_location: europe-west9
      image_tag: ${{ github.sha }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      PASSCULTURE_GITHUB_ACTION_APP_ID: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}

  deploy-public-site-production:
    uses: ./.github/workflows/reusable_public_site_deploy.yml
    needs:
      - deploy-cms-production
    with:
      environment: production
      cluster_name: cls-metier-production
      gcp_project_id: passculture-cls-metier-prod
      cluster_location: europe-west9
      cms_url: https://siteinstit-cms.passculture.team
      backend_url: https://backend.passculture.app
      namespace: site-instit-production
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      PASSCULTURE_GITHUB_ACTION_APP_ID: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
