on: 
  workflow_dispatch:
    
name: Deploy production CMS and static website

jobs:
  deploy-cms-production:
    uses: ./.github/workflows/reusable_cms_deploy.yml
    with:
      environment: production 
      workload_identity_provider_secret_name: passculture-cls-metier-ehp/gcp_cls_metier_prod_workload_identity_provider 
      teleport_version: 13.4.4
      teleport_proxy: teleport.cls.passculture.team:443
      teleport_kubernetes_cluster: passculture-cls-metier-prod
      image_tag: ${{ github.sha }}
      secrets_project_id: passculture-cls-metier-ehp
    secrets:
      SECRETS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_CLS_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      SECRETS_SERVICE_ACCOUNT: ${{ secrets.GCP_CLS_EHP_SERVICE_ACCOUNT }}

  deploy-public-site-production:
    uses: ./.github/workflows/reusable_public_site_deploy.yml
    needs:
      - deploy-cms-production
    with:
      environment: production
      teleport_version: 13.4.4
      teleport_proxy: teleport.cls.passculture.team:443
      teleport_kubernetes_cluster: passculture-cls-metier-prod
      workload_identity_provider_secret_name: passculture-cls-metier-ehp/gcp_cls_metier_prod_workload_identity_provider 
      cms_url: https://siteinstit-cms.passculture.team
      backend_url: https://backend.passculture.app
      secrets_project_id: passculture-cls-metier-ehp
      namespace: site-instit-production
    secrets:
      SECRETS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_CLS_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      SECRETS_SERVICE_ACCOUNT: ${{ secrets.GCP_CLS_EHP_SERVICE_ACCOUNT }}
