on:
  workflow_dispatch:

name: Deploy staging public website

jobs:
  deploy-public-site-staging:
    uses: ./.github/workflows/reusable_public_site_deploy.yml
    with:
      environment: staging
      workload_identity_provider_secret_name: passculture-metier-ehp/gcp_metier_ehp_workload_identity_provider
      cms_url: https://siteinstit-cms.staging.passculture.team
      backend_url: https://backend.passculture.team
      secrets_project_id: passculture-metier-ehp
    secrets:
      SECRETS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      SECRETS_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
