on: 
  workflow_dispatch:
    
name: Deploy staging static website

jobs:
  deploy-staging:
    uses: ./.github/workflows/reusable_deploy.yml
    with:
      environment: staging
      workload_identity_provider_secret_name: passculture-metier-ehp/gcp_metier_ehp_workload_identity_provider 
    secrets:
      SECRETS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      SECRETS_SERVICE_ACCOUNT: ${{ secrets.GCP_EHP_SERVICE_ACCOUNT }}
      

