on:
  workflow_dispatch:

name: Deploy testing public website

jobs:
  deploy-public-site-testing:
    uses: ./.github/workflows/reusable_public_site_deploy.yml
    with:
      environment: testing
      workload_identity_provider_secret_name: passculture-cls-metier-ehp/gcp_metier_cls_ehp_workload_identity_provider
      cms_url: https://siteinstit-cms.testing.passculture.team
      backend_url: https://backend.testing.passculture.team
      secrets_project_id: passculture-cls-metier-ehp
    secrets:
      SECRETS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_CLS_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      SECRETS_SERVICE_ACCOUNT: ${{ secrets.GCP_CLS_EHP_SERVICE_ACCOUNT }}

