on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

name: Deploy testing public website

jobs:
  deploy-public-site-testing:
    uses: ./.github/workflows/reusable_public_site_deploy.yml
    with:
      environment: testing
      workload_identity_provider_secret_name: passculture-cls-metier-ehp/gcp_metier_cls_ehp_workload_identity_provider
      cms_url: https://siteinstit-cms.testing.passculture.team
      backend_url: https://backend.passculture.app
      secrets_project_id: passculture-cls-metier-ehp
      namespace: site-instit-testing
      cluster_scope: cls-metier
      cluster_environment: ehp
    secrets:
      SECRETS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_CLS_EHP_WORKLOAD_IDENTITY_PROVIDER }}
      SECRETS_SERVICE_ACCOUNT: ${{ secrets.GCP_CLS_EHP_SERVICE_ACCOUNT }}
      PASSCULTURE_GITHUB_ACTION_APP_ID: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
