on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

name: Deploy testing public website

jobs:
  deploy-public-site-testing:
    uses: ./.github/workflows/reusable_public_site_deploy.yml
    with:
      environment: testing
      cms_url: https://siteinstit-cms.testing.passculture.team
      backend_url: https://backend.passculture.app
      namespace: site-instit-testing
      cluster_name: cls-metier-ehp
      gcp_project_id: passculture-cls-metier-ehp
      cluster_location: europe-west9
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      PASSCULTURE_GITHUB_ACTION_APP_ID: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
