name: Deploy public site
on:
  workflow_call:
    inputs:
      project_id:
        type: string
        description: GCP Project id to use
        required: true
      environment:
        type: string
        description: Environment to deploy
        required: true
      image_tag:
        type: string
        description: Image tag to deploy
        required: true
      cluster_name:
        type: string
        required: true
      cluster_location:
        type: string
        required: true
      gcp_project_id:
        type: string
        required: true
      argocd_version:
        type: string
        required: false
        default: v2.8.4
    secrets:
      SLACK_BOT_TOKEN:
        required: true
        description: A token to send message through slack
      PASSCULTURE_GITHUB_ACTION_APP_ID:
        required: true
        description: "Github Application ID to use to clone other repos"
      PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY:
        required: true
        description: "Private key for the Github application used to clone other repos"

jobs:
  deploy-cms:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-22.04
    environment:
      name: site-instit-${{ inputs.environment }}
      deployment: true 
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc09333" # v3.0.0
        id: google-auth
        with:
          create_credentials_file: true
          token_format: "access_token"
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PRD }}
          service_account: ${{ vars.SITE_INSTIT_CD_SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db" # v3.0.1

      - name: "Docker login"
        id: "docker-login"
        uses: "docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2" # v4.0.0
        with:
          registry: "europe-west1-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.google-auth.outputs.access_token }}"

      - name: Authenticate through github app ghactionci
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: github-token
        with:
          app-id: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_ID }}
          private-key: ${{ secrets.PASSCULTURE_GITHUB_ACTION_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          # Liste des repositories à cloner
          repositories: |
            infrastructure
            pass-culture-institutional
            rendered-manifests
            pc-render-manifests
            pc-connect
            pc-firestore-cli
          permission-contents: write

      - name: "Setup helmfile"
        uses: mamezou-tech/setup-helmfile@c04e83ec7650bf2ec910864bcb409479cf56d8e6 # v2.2.0
        with:
          helmfile-version: "v1.1.3"

      # Executes helmfile templating and push results to render-manifests repository
      - name: "Setup pc-render-manifests"
        uses: pass-culture/common-workflows/actions/setup-pc-render-manifests@setup-pc-render-manifests/v0.1.0
        with:
          token: ${{ steps.github-token.outputs.token }}
          version: "v0.7.1"

      - name: "Generate and push rendered manifests"
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ steps.github-token.outputs.token }}
          ENVIRONMENT: ${{ inputs.environment }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          pc-render-manifests render \
            -a site-instit \
            -e "$ENVIRONMENT" \
            --sourceRepoURL https://github.com/pass-culture/infrastructure.git \
            --sourcePath helm/site-instit \
            --sourceRepoRef main \
            --additionalArg "--set deployment.image.tag=$IMAGE_TAG" \
            --commitMsg "sit-instit($ENVIRONMENT) : manifests for app_version=$IMAGE_TAG" \
            --clean=false \
            --push \
            --silent

      - name: Authenticate to GKE cluster
        uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395 # v3.0.0
        with:
          cluster_name: ${{ inputs.cluster_name }}
          project_id: ${{ inputs.gcp_project_id }}
          location: ${{ inputs.cluster_location }}
          use_dns_based_endpoint: true

      - name: Sync argoCD application
        uses: pass-culture/common-workflows/actions/argocd-sync@argocd-sync/v0.8.0
        with:
          app_name: site-instit-${{ inputs.environment }}
          argocd_app_wait: true


  notification:
    name: "Notification"
    runs-on: ubuntu-22.04
    permissions: {}
    needs: 
      - deploy-cms
    if: ${{ always() }}
    steps:
      - name: "Post to a Slack channel on success"
        if: ${{ always() && contains(needs.deploy-cms.result, 'success') }}
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
        with:
          # channel #alertes-deploiement-site-instit
          channel-id: "C06EKUL552T"
          payload: |
            {
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "color": "#36A64F",
                  "author_name": "${{github.actor}}",
                  "author_link": "https://github.com/${{github.actor}}",
                  "author_icon": "https://github.com/${{github.actor}}.png",
                  "title": "CMS Site instit",
                  "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
                  "text": "Le CMS du site instit vient d'être déployé en ${{ inputs.environment }} :white_check_mark:"
                }
              ],
              "unfurl_links": false,
              "unfurl_media": false
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: "Post to a Slack channel on failure"
        if: ${{ always() && contains(needs.deploy-cms.result, 'failure') }}
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
        with:
          # channel #alertes-deploiement-site-instit
          channel-id: "C06EKUL552T"
          payload: |
            {
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "color": "#A30002",
                  "author_name": "${{github.actor}}",
                  "author_link": "https://github.com/${{github.actor}}",
                  "author_icon": "https://github.com/${{github.actor}}.png",
                  "title": "CMS Site Instit",
                  "title_link": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}",
                  "text": "Le déploiement du CMS site instit vient d'échouer en ${{ inputs.environment }} :boom:"
                }
              ],
              "unfurl_links": false,
              "unfurl_media": false
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
